export const FETCH_USER = 'FETCH_USER';
export const CREATE_SURVEY = 'CREATE_SURVEY';
export const SURVEY_LOADING = 'SET_LOADING';
export const SURVEY_ERROR = 'SURVEY_ERROR';
export const FETCH_SURVEYS = 'FETCH_SURVEYS';
export const FETCH_CURRENT_SURVEY = 'FETCH_CURRENT_SURVEY';
